trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'sclask-app'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'SclaskContainerRegistr'
    repository: 'sclask'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      